apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: sjekk
  namespace: default
  labels:
    team: tbd
  annotations:
    zone: fss
spec:
  image: repo.adeo.no:5443/dp-kafka-offset-monitor:a4eed47
  port: 8080
  liveness:
    path: isAlive
  readiness:
    path: isReady
  replicas:
    min: 1
    max: 1
  resources:
    limits:
      cpu: 1000m
      memory: 384Mi
    requests:
      cpu: 100m
      memory: 256Mi
  prometheus:
    enabled: true
    path: /metrics
  vault:
    enabled: true
  env:
    - name: PROMETHEUS_NAMESPACE
      value: default
    - name: CONSUMER_GROUPS
      value: spleis-v3,sparkel-sykepengeperioder-v1,sputnik-v1,spock-v1,spenn-1,spade-v3,behovsakkumulator-v1,vedtaksfeed-v1,sparkel-vilkarsproving-v1,sparkel-inntekt-v1,spetakkel-v1
    - name: KAFKA_BOOTSTRAP_SERVERS
      value: a01apvl00145.adeo.no:8443,a01apvl00146.adeo.no:8443,a01apvl00147.adeo.no:8443,a01apvl00148.adeo.no:8443,a01apvl00149.adeo.no:8443,a01apvl00150.adeo.no:8443
